// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuarentenarioWeb.Data;

#nullable disable

namespace QuarentenarioWeb.Migrations.Quarentenario
{
    [DbContext(typeof(QuarentenarioContext))]
    [Migration("20260329224642_InitialBaseline")]
    partial class InitialBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspNetUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetUserRoles_RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("MaterialPatogeno", b =>
                {
                    b.Property<int>("IdMaterial")
                        .HasColumnType("int")
                        .HasColumnName("idMaterial");

                    b.Property<int>("IdPatogeno")
                        .HasColumnType("int")
                        .HasColumnName("idPatogeno");

                    b.HasKey("IdMaterial", "IdPatogeno");

                    b.HasIndex("IdPatogeno");

                    b.ToTable("MaterialPatogeno", (string)null);
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.Analise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("dataInicio")
                        .HasDefaultValueSql("(getdate())", "DF_AnaliseDetalhe_DataInicio");

                    b.Property<DateTime?>("DataTermino")
                        .HasColumnType("datetime")
                        .HasColumnName("dataTermino");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("descricao");

                    b.Property<bool>("Finalizada")
                        .HasColumnType("bit")
                        .HasColumnName("finalizada");

                    b.Property<int>("IdBoletim")
                        .HasColumnType("int")
                        .HasColumnName("idBoletim");

                    b.Property<int>("IdPatogeno")
                        .HasColumnType("int")
                        .HasColumnName("idPatogeno");

                    b.Property<bool>("Positivo")
                        .HasColumnType("bit")
                        .HasColumnName("positivo");

                    b.HasKey("Id")
                        .HasName("PK_AnaliseDetalhe");

                    b.HasIndex("IdBoletim");

                    b.HasIndex("IdPatogeno");

                    b.ToTable("Analise", (string)null);
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.Anexo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdAnalise")
                        .HasColumnType("int")
                        .HasColumnName("idAnalise");

                    b.Property<int?>("IdBoletim")
                        .HasColumnType("int")
                        .HasColumnName("idBoletim");

                    b.Property<string>("NomeArmazenado")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("nomeArmazenado");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("nomeArquivo");

                    b.Property<string>("TipoConteudo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tipoConteudo");

                    b.HasKey("Id");

                    b.HasIndex("IdAnalise");

                    b.HasIndex("IdBoletim");

                    b.ToTable("Anexo", (string)null);
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.AspNetRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NormalizedName" }, "RoleNameIndex")
                        .IsUnique()
                        .HasFilter("([NormalizedName] IS NOT NULL)");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.AspNetRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetRoleClaims_RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.AspNetUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NormalizedEmail" }, "EmailIndex");

                    b.HasIndex(new[] { "NormalizedUserName" }, "UserNameIndex")
                        .IsUnique()
                        .HasFilter("([NormalizedUserName] IS NOT NULL)");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.AspNetUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserClaims_UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.AspNetUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserLogins_UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.AspNetUserToken", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.Boletim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("dataInicio")
                        .HasDefaultValueSql("(getdate())", "DF_Analise_DataInicio");

                    b.Property<DateTime?>("DataTermino")
                        .HasColumnType("datetime")
                        .HasColumnName("dataTermino");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("descricao");

                    b.Property<bool>("Finalizada")
                        .HasColumnType("bit")
                        .HasColumnName("finalizada");

                    b.Property<int>("IdMaterial")
                        .HasColumnType("int")
                        .HasColumnName("idMaterial");

                    b.Property<int>("IdPais")
                        .HasColumnType("int")
                        .HasColumnName("idPais");

                    b.Property<bool>("Positivo")
                        .HasColumnType("bit")
                        .HasColumnName("positivo");

                    b.HasKey("Id")
                        .HasName("PK_Analise");

                    b.HasIndex("IdMaterial");

                    b.HasIndex("IdPais");

                    b.ToTable("Boletim", (string)null);
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.Importacao", b =>
                {
                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Patogeno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TipoControle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TipoPatageno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.ToTable("Importacao", (string)null);
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("Material", (string)null);
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.Pai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("Pais");
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.Patogeno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdTipoControle")
                        .HasColumnType("int")
                        .HasColumnName("idTipoControle");

                    b.Property<int>("IdTipoPatogeno")
                        .HasColumnType("int")
                        .HasColumnName("idTipoPatogeno");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("IdTipoControle");

                    b.HasIndex("IdTipoPatogeno");

                    b.HasIndex(new[] { "Nome", "IdTipoPatogeno", "IdTipoControle" }, "UX_Patogeno_Nome_IdTipoPatogeno_IdTipoControle")
                        .IsUnique();

                    b.ToTable("Patogeno", (string)null);
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.TipoControle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("TipoControle", (string)null);
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.TipoPatogeno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("TipoPatogeno", (string)null);
                });

            modelBuilder.Entity("AspNetUserRole", b =>
                {
                    b.HasOne("QuarentenarioWeb.Models.AspNetRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuarentenarioWeb.Models.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MaterialPatogeno", b =>
                {
                    b.HasOne("QuarentenarioWeb.Models.Material", null)
                        .WithMany()
                        .HasForeignKey("IdMaterial")
                        .IsRequired()
                        .HasConstraintName("FK_MaterialPatogeno_Material");

                    b.HasOne("QuarentenarioWeb.Models.Patogeno", null)
                        .WithMany()
                        .HasForeignKey("IdPatogeno")
                        .IsRequired()
                        .HasConstraintName("FK_MaterialPatogeno_Patogeno");
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.Analise", b =>
                {
                    b.HasOne("QuarentenarioWeb.Models.Boletim", "IdBoletimNavigation")
                        .WithMany("Analises")
                        .HasForeignKey("IdBoletim")
                        .IsRequired()
                        .HasConstraintName("FK_Analise_Boletim");

                    b.HasOne("QuarentenarioWeb.Models.Patogeno", "IdPatogenoNavigation")
                        .WithMany("Analises")
                        .HasForeignKey("IdPatogeno")
                        .IsRequired()
                        .HasConstraintName("FK_Analise_Patogeno");

                    b.Navigation("IdBoletimNavigation");

                    b.Navigation("IdPatogenoNavigation");
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.Anexo", b =>
                {
                    b.HasOne("QuarentenarioWeb.Models.Analise", "IdAnaliseNavigation")
                        .WithMany("Anexos")
                        .HasForeignKey("IdAnalise")
                        .HasConstraintName("FK_Anexo_Analise");

                    b.HasOne("QuarentenarioWeb.Models.Boletim", "IdBoletimNavigation")
                        .WithMany("Anexos")
                        .HasForeignKey("IdBoletim")
                        .HasConstraintName("FK_Anexo_Boletim");

                    b.Navigation("IdAnaliseNavigation");

                    b.Navigation("IdBoletimNavigation");
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.AspNetRoleClaim", b =>
                {
                    b.HasOne("QuarentenarioWeb.Models.AspNetRole", "Role")
                        .WithMany("AspNetRoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.AspNetUserClaim", b =>
                {
                    b.HasOne("QuarentenarioWeb.Models.AspNetUser", "User")
                        .WithMany("AspNetUserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.AspNetUserLogin", b =>
                {
                    b.HasOne("QuarentenarioWeb.Models.AspNetUser", "User")
                        .WithMany("AspNetUserLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.AspNetUserToken", b =>
                {
                    b.HasOne("QuarentenarioWeb.Models.AspNetUser", "User")
                        .WithMany("AspNetUserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.Boletim", b =>
                {
                    b.HasOne("QuarentenarioWeb.Models.Material", "IdMaterialNavigation")
                        .WithMany("Boletims")
                        .HasForeignKey("IdMaterial")
                        .IsRequired()
                        .HasConstraintName("FK_Boletim_Material");

                    b.HasOne("QuarentenarioWeb.Models.Pai", "IdPaisNavigation")
                        .WithMany("Boletims")
                        .HasForeignKey("IdPais")
                        .IsRequired()
                        .HasConstraintName("FK_Boletim_Pais");

                    b.Navigation("IdMaterialNavigation");

                    b.Navigation("IdPaisNavigation");
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.Patogeno", b =>
                {
                    b.HasOne("QuarentenarioWeb.Models.TipoControle", "IdTipoControleNavigation")
                        .WithMany("Patogenos")
                        .HasForeignKey("IdTipoControle")
                        .IsRequired()
                        .HasConstraintName("FK_Patogeno_TipoControle");

                    b.HasOne("QuarentenarioWeb.Models.TipoPatogeno", "IdTipoPatogenoNavigation")
                        .WithMany("Patogenos")
                        .HasForeignKey("IdTipoPatogeno")
                        .IsRequired()
                        .HasConstraintName("FK_Patogeno_TipoPatogeno");

                    b.Navigation("IdTipoControleNavigation");

                    b.Navigation("IdTipoPatogenoNavigation");
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.Analise", b =>
                {
                    b.Navigation("Anexos");
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.AspNetRole", b =>
                {
                    b.Navigation("AspNetRoleClaims");
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.AspNetUser", b =>
                {
                    b.Navigation("AspNetUserClaims");

                    b.Navigation("AspNetUserLogins");

                    b.Navigation("AspNetUserTokens");
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.Boletim", b =>
                {
                    b.Navigation("Analises");

                    b.Navigation("Anexos");
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.Material", b =>
                {
                    b.Navigation("Boletims");
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.Pai", b =>
                {
                    b.Navigation("Boletims");
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.Patogeno", b =>
                {
                    b.Navigation("Analises");
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.TipoControle", b =>
                {
                    b.Navigation("Patogenos");
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.TipoPatogeno", b =>
                {
                    b.Navigation("Patogenos");
                });
#pragma warning restore 612, 618
        }
    }
}
