// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuarentenarioWeb.Data;

#nullable disable

namespace QuarentenarioWeb.Migrations.Quarentenario
{
    [DbContext(typeof(QuarentenarioContext))]
    partial class QuarentenarioContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MaterialPatogeno", b =>
                {
                    b.Property<int>("IdMaterial")
                        .HasColumnType("int")
                        .HasColumnName("idMaterial");

                    b.Property<int>("IdPatogeno")
                        .HasColumnType("int")
                        .HasColumnName("idPatogeno");

                    b.HasKey("IdMaterial", "IdPatogeno");

                    b.HasIndex("IdPatogeno");

                    b.ToTable("MaterialPatogeno", (string)null);
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.Analise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("dataInicio")
                        .HasDefaultValueSql("(getdate())", "DF_Analise_DataInicio");

                    b.Property<DateTime?>("DataTermino")
                        .HasColumnType("datetime")
                        .HasColumnName("dataTermino");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("descricao");

                    b.Property<bool>("Finalizada")
                        .HasColumnType("bit")
                        .HasColumnName("finalizada");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("idCliente");

                    b.Property<int>("IdMaterial")
                        .HasColumnType("int")
                        .HasColumnName("idMaterial");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdMaterial");

                    b.ToTable("Analise", (string)null);
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.AnaliseDetalhe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("dataInicio")
                        .HasDefaultValueSql("(getdate())", "DF_AnaliseDetalhe_DataInicio");

                    b.Property<DateTime?>("DataTermino")
                        .HasColumnType("datetime")
                        .HasColumnName("dataTermino");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("descricao");

                    b.Property<bool>("Finalizada")
                        .HasColumnType("bit")
                        .HasColumnName("finalizada");

                    b.Property<int>("IdAnalise")
                        .HasColumnType("int")
                        .HasColumnName("idAnalise");

                    b.Property<int>("IdPatogeno")
                        .HasColumnType("int")
                        .HasColumnName("idPatogeno");

                    b.HasKey("Id");

                    b.HasIndex("IdAnalise");

                    b.HasIndex("IdPatogeno");

                    b.ToTable("AnaliseDetalhe", (string)null);
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.Anexo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdAnalise")
                        .HasColumnType("int")
                        .HasColumnName("idAnalise");

                    b.Property<int?>("IdAnaliseDetalhe")
                        .HasColumnType("int")
                        .HasColumnName("idAnaliseDetalhe");

                    b.Property<string>("NomeArmazenado")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("nomeArmazenado");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("nomeArquivo");

                    b.Property<string>("TipoConteudo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tipoConteudo");

                    b.HasKey("Id");

                    b.HasIndex("IdAnalise");

                    b.HasIndex("IdAnaliseDetalhe");

                    b.ToTable("Anexo", (string)null);
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("Pais", (string)null);
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.Importacao", b =>
                {
                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Patogeno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TipoControle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TipoPatageno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.ToTable("Importacao", (string)null);
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("Material", (string)null);
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.Patogeno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdTipoControle")
                        .HasColumnType("int")
                        .HasColumnName("idTipoControle");

                    b.Property<int>("IdTipoPatogeno")
                        .HasColumnType("int")
                        .HasColumnName("idTipoPatogeno");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("IdTipoControle");

                    b.HasIndex("IdTipoPatogeno");

                    b.HasIndex("Nome", "IdTipoPatogeno", "IdTipoControle")
                        .IsUnique()
                        .HasDatabaseName("UX_Patogeno_Nome_IdTipoPatogeno_IdTipoControle");

                    b.ToTable("Patogeno", (string)null);
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.TipoControle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("TipoControle", (string)null);
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.TipoPatogeno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("TipoPatogeno", (string)null);
                });

            modelBuilder.Entity("MaterialPatogeno", b =>
                {
                    b.HasOne("QuarentenarioWeb.Models.Material", null)
                        .WithMany()
                        .HasForeignKey("IdMaterial")
                        .IsRequired()
                        .HasConstraintName("FK_MaterialPatogeno_Material");

                    b.HasOne("QuarentenarioWeb.Models.Patogeno", null)
                        .WithMany()
                        .HasForeignKey("IdPatogeno")
                        .IsRequired()
                        .HasConstraintName("FK_MaterialPatogeno_Patogeno");
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.Analise", b =>
                {
                    b.HasOne("QuarentenarioWeb.Models.Pais", "IdClienteNavigation")
                        .WithMany("Analises")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("FK_Analise_Cliente");

                    b.HasOne("QuarentenarioWeb.Models.Material", "IdMaterialNavigation")
                        .WithMany("Analises")
                        .HasForeignKey("IdMaterial")
                        .IsRequired()
                        .HasConstraintName("FK_Analise_Material");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdMaterialNavigation");
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.AnaliseDetalhe", b =>
                {
                    b.HasOne("QuarentenarioWeb.Models.Analise", "IdAnaliseNavigation")
                        .WithMany("AnaliseDetalhes")
                        .HasForeignKey("IdAnalise")
                        .IsRequired()
                        .HasConstraintName("FK_AnaliseDetalhe_Analise");

                    b.HasOne("QuarentenarioWeb.Models.Patogeno", "IdPatogenoNavigation")
                        .WithMany("AnaliseDetalhes")
                        .HasForeignKey("IdPatogeno")
                        .IsRequired()
                        .HasConstraintName("FK_AnaliseDetalhe_Patogeno");

                    b.Navigation("IdAnaliseNavigation");

                    b.Navigation("IdPatogenoNavigation");
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.Anexo", b =>
                {
                    b.HasOne("QuarentenarioWeb.Models.Analise", "IdAnaliseNavigation")
                        .WithMany("Anexos")
                        .HasForeignKey("IdAnalise")
                        .HasConstraintName("FK_Anexo_Analise");

                    b.HasOne("QuarentenarioWeb.Models.AnaliseDetalhe", "IdAnaliseDetalheNavigation")
                        .WithMany("Anexos")
                        .HasForeignKey("IdAnaliseDetalhe")
                        .HasConstraintName("FK_Anexo_AnaliseDetalhe");

                    b.Navigation("IdAnaliseDetalheNavigation");

                    b.Navigation("IdAnaliseNavigation");
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.Patogeno", b =>
                {
                    b.HasOne("QuarentenarioWeb.Models.TipoControle", "IdTipoControleNavigation")
                        .WithMany("Patogenos")
                        .HasForeignKey("IdTipoControle")
                        .IsRequired()
                        .HasConstraintName("FK_Patogeno_TipoControle");

                    b.HasOne("QuarentenarioWeb.Models.TipoPatogeno", "IdTipoPatogenoNavigation")
                        .WithMany("Patogenos")
                        .HasForeignKey("IdTipoPatogeno")
                        .IsRequired()
                        .HasConstraintName("FK_Patogeno_TipoPatogeno");

                    b.Navigation("IdTipoControleNavigation");

                    b.Navigation("IdTipoPatogenoNavigation");
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.Analise", b =>
                {
                    b.Navigation("AnaliseDetalhes");

                    b.Navigation("Anexos");
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.AnaliseDetalhe", b =>
                {
                    b.Navigation("Anexos");
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.Pais", b =>
                {
                    b.Navigation("Analises");
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.Material", b =>
                {
                    b.Navigation("Analises");
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.Patogeno", b =>
                {
                    b.Navigation("AnaliseDetalhes");
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.TipoControle", b =>
                {
                    b.Navigation("Patogenos");
                });

            modelBuilder.Entity("QuarentenarioWeb.Models.TipoPatogeno", b =>
                {
                    b.Navigation("Patogenos");
                });
#pragma warning restore 612, 618
        }
    }
}
